# Python.Random Overview

**The content below has been adapted from the [numpy.random API](https://numpy.org/doc/stable/reference/random/index.html#) source with some changes. Look at the documentation section for more details.** 

random is a module within the numpy library used to work with random numbers. 

Can the python program make truly random number? 

No. Random number generated with Python is not fully random in the scientific sense of the word but *pseudorandom* - generated with a pseudorandom number generator (PRNG), which is essentially any algorithm for generating seemingly random but still reproducible data. [[6]](#References)
 
PRNG starts with a random number, known as the seed, and then uses an algorithm to generate a pseudo-random sequence of bits based on it. random.seed() function call is seeding the underlying random number generator (PRNG) and this is what makes subsequent calls to generate random numbers deterministic. [[6]](#References)

Numpy’s random number routines produce pseudorandom numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

* BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.
* Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval. [[1]](#References)

## Documentation
* [Numpy manual - latest version](https://numpy.org/doc/stable/index.html)
* [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)
* [Random generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator)
* [Bit Generators](https://numpy.org/doc/stable/reference/random/bit_generators/index.html#)

## Simple examples to start

Adapted from the [W3Schools](https://www.w3schools.com/python/numpy/numpy_random.asp) tutorial. 

In [8]:
from numpy import random

# Generate a random integer from 0 to 100:
x = random.randint(100) 
print(x)

34


The randint() method returns an integer number from the specified range.

In [12]:
# Generate a random float from 0 to 1:
x = random.random(9)
print(x)

[0.63347839 0.53473515 0.3669675  0.6006421  0.92726029 0.28142365
 0.88824681 0.57247045 0.13208553]


The random() method returns a random float number between 0 and 1. Generate a 1-D array containing 5 random floats:

In [10]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))
print(x)

[[75 21 75 80 80]
 [ 5 97 93 76 65]
 [51  3 61 95 71]]


In [11]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 3 9 9 7]
 [9 9 5 3 9]
 [3 9 9 5 9]]


## References 
1. Random sampling (numpy.random) — NumPy v1.21 Manual. (2008–2021). NumPy. Retrieved October 31, 2021, from https://numpy.org/doc/stable/reference/random/index.html
2. Random Generator — NumPy v1.21 Manual. (2008–2021). NumPy. Retrieved October 31, 2021, from https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator
3. Permuted Congruential Generator (64-bit, PCG64) — NumPy v1.21 Manual. (2008–2021). NumPy. Retrieved October 31, 2021, from https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html#numpy.random.PCG64
4. Ebner, J. (2021, July 24). NumPy Random Seed, Explained. Sharp Sight. Retrieved October 31, 2021, from https://www.sharpsightlabs.com/blog/numpy-random-seed/
5. Introduction to Random Numbers in NumPy. (1999–2021). W3schools. Retrieved October 31, 2021, from https://www.w3schools.com/python/numpy/numpy_random.asp
6. Real Python. (2021, April 3). Generating Random Data in Python (Guide). Retrieved October 31, 2021, from https://realpython.com/python-random/
7. random — Generate pseudo-random numbers — Python 3.10.0 documentation. (2001–2021). Python. Retrieved October 31, 2021, from https://docs.python.org/3/library/random.html
8. Jupyter Notebook Users Manual.ipynb. (n.d.). Jupyter at Bryn Mawr College. Retrieved November 2, 2021, from https://jupyter.brynmawr.edu/services/public/dblank/Jupyter%20Notebook%20Users%20Manual.ipynb#4.3.5-Notebook-Internal-Links