# Python.Random Overview

**The content below has been adapted from the [numpy.random API](https://numpy.org/doc/stable/reference/random/index.html#) source with some changes. Look at the documentation section for more details.** 

random is a module within the numpy library used to work with random numbers. 

Can the python program make truly random number? 

No. Random number generated with Python is not fully random in the scientific sense of the word but *pseudorandom* - generated with a pseudorandom number generator (PRNG), which is essentially any algorithm for generating seemingly random but still reproducible data. [[6]](#References)
 
PRNG starts with a random number, known as the seed, and then uses an algorithm to generate a pseudo-random sequence of bits based on it. random.seed() function call is seeding the underlying random number generator (PRNG) and this is what makes subsequent calls to generate random numbers deterministic. [[6]](#References)

Numpy’s random number routines produce pseudorandom numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

* BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.
* Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval. [[1]](#References)

## Documentation
* [Numpy manual - latest version](https://numpy.org/doc/stable/index.html)
* [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)
* [Random generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator)
* [Bit Generators](https://numpy.org/doc/stable/reference/random/bit_generators/index.html#)

## Generating simple random data using NumPy

**Adapted from the [W3Schools](https://www.w3schools.com/python/numpy/numpy_random.asp) tutorial [[5]](#References) and [TowardsDataScience](https://towardsdatascience.com/statistics-in-python-generating-random-numbers-in-python-numpy-and-sklearn-60e16b2210ae) [[10]](#References)**.

The random module contains several functions that allows you to generate random numbers.

The randint() function generates an integer numbers within the half-open interval:

In [1]:
from numpy import random

# Generate a random integer from [0 to 100):
x = random.randint(100) 
print(x)

16


You can also generate a list of integer values in multi-dimension:

In [2]:
# [0,100) in 2D array  
x = random.randint(100, size=(3, 5)) # ([0,100) x 5) x 3
print(x)

[[96 69 15  1 82]
 [ 5 52 77 42 71]
 [95 15 45 79 34]]


If you just want to generate foating point numbers in the half-open interval, there is a function rand() you can use:

In [3]:
# Generate a random float from [0 to 1):
x = random.rand(9)
print(x)

[0.24910886 0.24974657 0.95917313 0.07069068 0.67544205 0.3698565
 0.07714936 0.40482668 0.3273783 ]


The rand() function makes it easy to generate values of half-open interval in various dimensions:

In [4]:
# [0,1) in 2D array
x = random.rand(2,3) # ([0,100] x 3) x 2)
print(x)

[[0.14574946 0.10278572 0.68603617]
 [0.79413673 0.40582786 0.3638236 ]]


The choice() function generates random elements for the sequence of data:

In [5]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)
x = random.choice([3, 5, 7, 9], size=(3, 5)) # ((3, 5, 7, and 9) x 5) x 3
print(x)

[[3 3 9 9 9]
 [7 3 7 9 3]
 [3 5 9 7 3]]


## References 
1. Random sampling (numpy.random) — NumPy v1.21 Manual. (2008–2021). NumPy. Retrieved October 31, 2021, from https://numpy.org/doc/stable/reference/random/index.html
2. Random Generator — NumPy v1.21 Manual. (2008–2021). NumPy. Retrieved October 31, 2021, from https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator
3. Permuted Congruential Generator (64-bit, PCG64) — NumPy v1.21 Manual. (2008–2021). NumPy. Retrieved October 31, 2021, from https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html#numpy.random.PCG64
4. Ebner, J. (2021, July 24). NumPy Random Seed, Explained. Sharp Sight. Retrieved October 31, 2021, from https://www.sharpsightlabs.com/blog/numpy-random-seed/
5. Introduction to Random Numbers in NumPy. (1999–2021). W3schools. Retrieved October 31, 2021, from https://www.w3schools.com/python/numpy/numpy_random.asp
6. Real Python. (2021, April 3). Generating Random Data in Python (Guide). Retrieved October 31, 2021, from https://realpython.com/python-random/
7. random — Generate pseudo-random numbers — Python 3.10.0 documentation. (2001–2021). Python. Retrieved October 31, 2021, from https://docs.python.org/3/library/random.html
8. Jupyter Notebook Users Manual.ipynb. (n.d.). Jupyter at Bryn Mawr College. Retrieved November 2, 2021, from https://jupyter.brynmawr.edu/services/public/dblank/Jupyter%20Notebook%20Users%20Manual.ipynb#4.3.5-Notebook-Internal-Links
9. Python Random Module. (n.d.). W3schools. Retrieved November 7, 2021, from https://www.w3schools.com/python/module_random.asp
10. Lee, W. (2021, September 27). Statistics in Python — Generating Random Numbers in Python, NumPy, and sklearn. Toward Data Science. Retrieved November 7, 2021, from https://towardsdatascience.com/statistics-in-python-generating-random-numbers-in-python-numpy-and-sklearn-60e16b2210ae
11. Real Python. (2021, March 19). Python Statistics Fundamentals: How to Describe Your Data. Retrieved November 7, 2021, from https://realpython.com/python-statistics/